const users = [
   {
    id: 1,
    name: "Emmanuel",
    lastname:"Macron",
    email:"emmy.macron@gmail.com",
    address:"2 rue Chevalier",
    postcode: 33000,
    town: "Bordeaux",
    status:true,
    password:"voleur",
    RoleId:1
   },
   {
    id: 2,
    name: "Gabriel",
    lastname: "Attal",
    email: "gigi.attal@gmail.com",
    address: "35 Avenue de la République",
    postcode: 33000,
    town: "Bordeaux",
    status:true,
    password: "ptitvoleur",
    RoleId:2
   },
   {
    id: 3,
    name: "Rachida",
    lastname: "Dati",
    email: "rachida.d@gmail.com",
    address: "41 Rue des Augustins",
    postcode: 33000,
    town: "Bordeaux",
    status:true,
    password: "ptitvoleur",
    RoleId:2
    },
    {
    id: 4,
    name: "Gerald",
    lastname: "Darmanin",
    email: "gege.darmanin@gmail.com",
    address: "5 Cours Saint-Louis",
    postcode: 33000,
    town: "Bordeaux",
    status:true,
    password: "ptitvoleur",
    RoleId:2
    },
    {
    id: 5,
    name: "Elisabeth",
    lastname: "Borne",
    email: "zaza.borne@gmail.com",
    address: "5 Rue des Bahutiers",
    postcode: 33000,
    town: "Bordeaux",
    status:true,
    password: "ptitvoleur",
    RoleId:2
    },
    {
    id: 6,
    name: "Nicolas",
    lastname:"Sarkozy",
    email:"nico.sarkozy@gmail.com",
    address:"12 Quai Richelieu",
    postcode: 33000,
    town: "Bordeaux",
    status:true,
    password:"ptitvoleur",
    RoleId:2
    },
    {
    id: 7,
    name: "Marine",
    lastname: "Le Pen",
    email: "marine.lp@gmail.com",
    address: "73 Quai des Chartrons",
    postcode: 33000,
    town: "Bordeaux",
    status:true,
    password: "ptitvoleur",
    RoleId:2
    },
    {
    id: 8,
    name: "Eric",
    lastname: "Zemmour",
    email: "riri.zemmour@gmail.com",
    address: "36 Rue du Mirail",
    postcode: 33000,
    town: "Bordeaux",
    status:true,
    password: "ptitvoleur",
    RoleId:2
    },
    {
    id: 9,
    name: "Jacques",
    lastname: "Chirac",
    email: "jack.chirac@gmail.com",
    address: "174 Rue du Jardin public",
    postcode: 33300,
    town: "Bordeaux",
    status:false,
    password: "ptitvoleur",
    RoleId:2
    },
    {
    id: 10,
    name: "Roselyne",
    lastname: "Bachelot",
    email: "rosy@gmail.com",
    address: "15 Rue du Passage Saint-Georges",
    postcode: 33000,
    town: "Bordeaux",
    status:false,
    password: "ptitvoleur",
    RoleId:2
    },
    {
    id: 11,
    name: "Edouard",
    lastname:"Philippe",
    email:"ed.philippe@gmail.com",
    address:"5 Place de la Victoire",
    postcode: 33000,
    town: "Bordeaux",
    status:true,
    password:"voleur",
    RoleId:2
    },
    {
    id: 12,
    name: "Marlène",
    lastname: "Schiappa",
    email: "marlène.s@gmail.com",
    address: "2 Avenue Carnot",
    postcode: 33200,
    town: "Bordeaux",
    status:true,
    password: "ptitvoleur",
    RoleId:2
    },
    {
    id: 13,
    name: "Valérie",
    lastname: "Pecresse",
    email: "valou.pecresse@gmail.com",
    address: "2 Quai Louis XVIII",
    postcode: 33000,
    town: "Bordeaux",
    status:false,
    password: "ptitvoleur",
    RoleId:2
    },
    {
    id: 14,
    name: "Anne",
    lastname: "Hidalgo",
    email: "anne.h@gmail.com",
    address: "23 Rue Raze",
    postcode: 33000,
    town: "Bordeaux",
    status:false,
    password: "ptitvoleur",
    RoleId:2
    },
    {
    id: 15,
    name: "Jordan",
    lastname: "Bardella",
    email: "jojo.bardella@gmail.com",
    address: "56 Rue du Hamel",
    postcode: 33800,
    town: "Bordeaux",
    status:true,
    password: "ptitvoleur",
    RoleId:2
    },
    {
    id: 16,
    name: "Eric",
    lastname:"Ciotti",
    email:"riri.ciotti@gmail.com",
    address:"79 Rue Stehelin",
    postcode: 33200,
    town: "Bordeaux",
    status:false,
    password:"voleur",
    RoleId:2
    },
    {
    id: 17,
    name: "Bruno",
    lastname: "Lemaire",
    email: "nono.lemaire@gmail.com",
    address: "11 Place du Parlement",
    postcode: 33000,
    town: "Bordeaux",
    status:false,
    password: "ptitvoleur",
    RoleId:2
    },
    {
    id: 18,
    name: "François",
    lastname: "Fillon",
    email: "francois.fillon@gmail.com",
    address: "270 Avenue de la Liberation Charles de Gaulle",
    postcode: 33110,
    town: "Le Bouscat",
    status:false,
    password: "ptitvoleur",
    RoleId:2
    },
    {
    id: 19,
    name: "Alain",
    lastname: "Juppé",
    email: "linlin.juppe@gmail.com",
    address: "34 Avenue Jean Jaures",
    postcode: 33600,
    town: "Pessac",
    status:false,
    password: "ptitvoleur",
    RoleId:2
    },
    {
    id: 20,
    name: "Aurore",
    lastname: "Berge",
    email: "19 Rue Esprit des Lois",
    address: "35 Avenue de la République",
    postcode: 33000,
    town: "Bordeaux",
    status:false,
    password: "ptitvoleur",
    RoleId:2
    },
    {
    id: 21,
    name: "Prisca",
    lastname: "Thevenot",
    email: "pripri@gmail.com",
    address: "38 Rue des Remparts",
    postcode: 33000,
    town: "Bordeaux",
    status:false,
    password: "ptitvoleur",
    RoleId:2
    },
    {
    id: 22,
    name: "Sylvie",
    lastname: "Retailleau",
    email: "sisi.retailleau@gmail.com",
    address: "3 Place du Marche Chartrons",
    postcode: 33000,
    town: "Bordeaux",
    status:false,
    password: "ptitvoleur",
    RoleId:2
    },
    {
    id: 23,
    name: "Eric",
    lastname: "Dupond-Moretti",
    email: "eric.dp@gmail.com",
    address: "104 Rue Frederic Sevene",
    postcode: 33004,
    town: "Talence",
    status:false,
    password: "ptitvoleur",
    RoleId:2
    },
    {
    id: 24,
    name: "François",
    lastname: "Hollande",
    email: "fh@gmail.com",
    address: "269 rue Judaique",
    postcode: 33000,
    town: "Bordeaux",
    status:true,
    password: "ptitvoleur",
    RoleId:2
    },
    {
    id: 25,
    name: "Nadine",
    lastname: "Morano",
    email: "nana.m@gmail.com",
    address: "18 place PeyBerland",
    postcode: 33000,
    town: "Bordeaux",
    status:false,
    password: "ptitvoleur",
    RoleId:2
    },
];
 
 module.exports = users 